version: '3.8'
services:
  frpc:
    image: snowdreamtech/frpc:0.48.0
    restart: always
    network_mode: host
    volumes:
    - ./frpc.ini:/etc/frp/frpc.ini:ro
    - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
