version: '3.8'
services:
  nginx:
    image: nginx:1.25.2
    restart: always
    network_mode: host
    # ports:
    # - 80:80
    # - 443:443
    volumes:
    - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./nginx/certs:/etc/nginx/certs
